competition:
  name: default
  metric: wape
  lag: execution
  min_dfu_rows: 3
  champion_model_id: champion
  models:
  - lgbm_global
  - lgbm_cluster
  - lgbm_transfer
  - catboost_global
  - catboost_cluster
  - xgboost_global
  - xgboost_cluster
  - prophet_global
  - prophet_pooled
